### ISSUE TITLE
Script variable references don't match up to docker environment variables

### ISSUE THREAD

**Issue by tjrmentor** [terraform-docs/gh-actions#72]
### Describe the bug
Using this action in my workflow, the environment variables are set for the docker container like so:
![image](https://user-images.githubusercontent.com/13069944/144926106-977e03b7-00c1-4592-8bf7-d5a83945b668.png)
Note that some input values that are two words long are upper kebab case, so the full variable name is something like `INPUT_OUTPUT-METHOD`.

The script doesn't not reference these environment variables correctly in many cases; for instance, https://github.com/terraform-docs/gh-actions/blob/main/src/docker-entrypoint.sh#L113, where it  references `INPUT_OUTPUT_METHOD`, and so the condition is never fulfilled.

### How can we reproduce it?
- Create a new, minimal repository with some terraform and an output file, say README.md, containing the injection tokens.
- Create a .github/workflows folder, and a workflow file within that folder
- Use the action with the following inputs: 
  output-file: README.md
- Trigger the workflow however you like
- Note that the default input value for output-method should be inject, and thus we should see a debug message as shown [here](https://github.com/terraform-docs/gh-actions/blob/main/src/docker-entrypoint.sh#L113)

### Environment information
terraform-docs/gh-actions@36c9547386018d8a99388b7c0e369c65e3b21cb1
Ubuntu OS Github hosted runner

**Comment by khos2ow** [comment]
Your observation is correct, but the functionality is fundamentally not broken as well.

The way GitHub auto-injects variables are that it's going to prefix them with `INPUT_` and uppercase them (i.e. `OUTPUT-METHOD` for [`output-method`](https://github.com/terraform-docs/gh-actions/blob/main/action.yml#L34)). But, use of `-` (hyphen) in a bash environment variable is not possible so `INPUT_OUTPUT-METHOD` is an illegal naming convention.

In order to keep using hyphen-separated (kebab-case) naming of actions' variables, we opted to manually, and explicitly, define them [here](https://github.com/terraform-docs/gh-actions/blob/main/action.yml#L89-L107). So at the end of the day both of these will get injected, i.e. `INPUT_OUTPUT-METHOD` and `INPUT_OUTPUT_METHOD`, which the script uses the latter.
